### PR TITLE
Feature/RSA-39, RSA-32, RSA-41, RSA-40

### PR DESCRIPTION
**Pull request by RossaMania**
Here's a rundown of what's new:

New Features 🌟
Display Food Details on Click: Now you can click on a food item to view its detailed information.
React Router Integration: Installed react-router and react-router-dom to enable seamless navigation.
Browser Route Setup: Created a Browser Route and added a home screen route for better app navigation.
PrivateRoute Component: Added a PrivateRoute component to protect authenticated routes.
Login Screen Route: Added a route for the login screen to enhance user authentication.
Food Menu Screen Route: Added a route for the food menu screen with comments for clarity.
Food Details Route: Added a "/food/" route for the FoodCard component to display detailed food information.
AuthSlice Reducer: Created an authSlice reducer to manage user authentication information.
Navbar NavLinks: Set up NavLinks in the Navbar for improved navigation and renamed the "food" route to "foods".
OurFoodsList Component: Created the OurFoodsList component to display a comprehensive list of all foods.
Improvements 🛠️
Code Cleanup: Removed unused code and added Outlet and Footer components to App.js.
Food Menu Functionality: Improved food menu functionality by adding a selected category state.
FoodCard Component Layout: Updated the layout of the FoodCard component and refined the routes.

### CODE REVIEW

**Comment by RossaMania** [comment]
image

**Comment by RossaMania** [comment]
image

**Comment by RossaMania** [comment]
image

image

**Comment by Nandhini0123** [comment]
Great work Ross!

**Pull request merged**
