### PR TITLE
Fix layout

### PR DESCRIPTION
**Pull request by RossaMania**
Here’s a summary of what’s new:

Improved Layout & Styling:

Added some padding between the Navbar and the Outlet to enhance visual separation. 🧩
Reduced padding between Navbar and Outlet for a cleaner look. ✨
Deleted the Footer from HomeScreen and removed unused Navbar and Footer components to streamline our layout. 🗑️
Set the FoodRibbon component in App.jsx, placing it above the Outlet for consistent visibility across the app. 🌟
Updated the FoodRibbon button color to our chosen shade of purple, and commented out unneeded code to keep things tidy. 💜
Implemented category selection functionality in the FoodRibbon to improve user experience. 🎯
New Feature Additions:

Created a barebones screen for Login and integrated basic login functionality to get us started. 🚀
Wired up the “Get Started” button in the Navbar to navigate directly to the Login page, streamlining our user flow. 🔗
Code Clean-Up:

Commented out an unused error variable in the FoodRibbon component, keeping our codebase clean and efficient. 🧹

### CODE REVIEW

**Comment by RossaMania** [comment]
image
image

**Comment by RossaMania** [comment]
image
image

**Review by k-kenney — COMMENTED** [review]
For App.jsx, I'm wondering why the FoodRibbon is necessary in this file as it will be used on the homepage and dashboard only and style differently on each. Also, there are some pages that the Navbar and Footer won't be necessary - for example the login page doesn't need the Navbar or Footer. Maybe there's something I'm not understanding though. Could you explain a bit?

**Comment by RossaMania** [comment]
Great questions!

- I wrapped the Navbar and Footer around the Outlet in App to make it a SPA.
- i figured things like the LoginScreen were going to be modals with gray/black back drops. I thought thats whats going to make the route with orders so much fun--Redux Toolkit AND modals.
- Food Ribbon is in App.js for testing. Code is commented out in Homepage to prevent confusion and to try to not break what Oleg is working on. FoodRibbon is in bright colors for testing. FoodRibbon still needs a bit more work.

**Pull request merged**
