### PR TITLE
to add tips

### PR DESCRIPTION
**Pull request by Nandhini0123**
1. 
addtips
addtipspage
added tips 
2. Onclicking "add tips" button in orderScreen page,  it will allow the user to select tips %
3. Once selected, user could choose next to take thee user again back to "orderScreen" page
4. tips value can be accessed across all components as it is created using Redux  toolkit

### CODE REVIEW

**Comment by RossaMania** [comment]
image

I don't see my 18% tip added?
49 + 10 + 7.35 = 66.35.
Same output when clicking on the 50% tip button as well. I click what tip I want, and then click "Next" button.

**Comment by RossaMania** [comment]
I'm looking at the code, and the setTips action is imported and defined, but never used in OrderScreen.

I don't see any lines of code that do math of tipSelected * itemsPrice? That may be an issue?

**Comment by Nandhini0123** [comment]
Will create a PR again after merging the "fix/shipping address bug" branch

**Comment by RossaMania** [comment]
I see the console logs!
image
Nice!

**Comment by RossaMania** [comment]
Per your message in Discord, I see the console logs! Nice! Should I reopen this pull request and merge?

**Pull request closed without merging**
